<a href="https://colab.research.google.com/github/josvalverde/MineriaDatos-Proyecto/blob/josseph_valverde/MineriaSteam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
# Para ver todas las columnas sin cortes
pd.set_option('display.max_columns', None)

In [3]:
# Cargar dataset
df = pd.read_csv("/content/steam.csv")

In [10]:
#Visualizar primeras 5 filas
df.head()

,appid,name,release_date,english,developer,publisher,platforms,required_age,categories,genres,steamspy_tags,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price,is_windows,is_mac,is_linux
0,10,Counter-Strike,2000-11-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,124534,3339,17612,317,10000000-20000000,7.19,True,True,True
1,20,Team Fortress Classic,1999-04-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,3318,633,277,62,5000000-10000000,3.99,True,True,True
2,30,Day of Defeat,2003-05-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Valve Anti-Cheat enabled,Action,FPS;World War II;Multiplayer,0,3416,398,187,34,5000000-10000000,3.99,True,True,True
3,40,Deathmatch Classic,2001-06-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,1273,267,258,184,5000000-10000000,3.99,True,True,True
4,50,Half-Life: Opposing Force,1999-11-01,1,Gearbox Software,Valve,windows;mac;linux,0,Single-player;Multi-player;Valve Anti-Cheat en...,Action,FPS;Action;Sci-fi,0,5250,288,624,415,5000000-10000000,3.99,True,True,True

In [11]:
# Visualizar ultimas 5 filas
df.tail()

,appid,name,release_date,english,developer,publisher,platforms,required_age,categories,genres,steamspy_tags,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price,is_windows,is_mac,is_linux
27070,1065230,Room of Pandora,2019-04-24,1,SHEN JIAWEI,SHEN JIAWEI,windows,0,Single-player;Steam Achievements,Adventure;Casual;Indie,Adventure;Indie;Casual,7,3,0,0,0,0-20000,2.09,True,False,False
27071,1065570,Cyber Gun,2019-04-23,1,Semyon Maximov,BekkerDev Studio,windows,0,Single-player,Action;Adventure;Indie,Action;Indie;Adventure,0,8,1,0,0,0-20000,1.69,True,False,False
27072,1065650,Super Star Blast,2019-04-24,1,EntwicklerX,EntwicklerX,windows,0,Single-player;Multi-player;Co-op;Shared/Split ...,Action;Casual;Indie,Action;Indie;Casual,24,0,1,0,0,0-20000,3.99,True,False,False
27073,1066700,New Yankee 7: Deer Hunters,2019-04-17,1,Yustas Game Studio,Alawar Entertainment,windows;mac,0,Single-player;Steam Cloud,Adventure;Casual;Indie,Indie;Casual;Adventure,0,2,0,0,0,0-20000,5.19,True,True,False
27074,1069460,Rune Lord,2019-04-24,1,Adept Studios GD,Alawar Entertainment,windows;mac,0,Single-player;Steam Cloud,Adventure;Casual;Indie,Indie;Casual;Adventure,0,4,0,0,0,0-20000,5.19,True,True,False

In [17]:
# Información del dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27075 entries, 0 to 27074
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   appid             27075 non-null  int64
 1   name              27075 non-null  object
 2   release_date      27075 non-null  object
 3   english           27075 non-null  int64
 4   developer         27074 non-null  object
 5   publisher         27061 non-null  object
 6   platforms         27075 non-null  object
 7   required_age      27075 non-null  int64
 8   categories        27075 non-null  object
 9   genres            27075 non-null  object
 10  steamspy_tags     27075 non-null  object
 11  achievements      27075 non-null  int64
 12  positive_ratings  27075 non-null  int64
 13  negative_ratings  27075 non-null  int64
 14  average_playtime  27075 non-null  int64
 15  median_playtime   27075 non-null  int64
 16  owners            27075 non-null  object
 17  price             27075 non-null  float64
 18  is_windows        27075 non-null  bool
 19  is_mac            27075 non-null  bool
 20  is_linux          27075 non-null  bool
dtypes: bool(3), float64(1), int64(8), object(9)
memory usage: 3.8+ MB

In [16]:
#devuelve cantidad de filas y columnas respectivamente
df.shape

(27075, 21)

In [9]:
# Separar columna "platforms"
df['is_windows'] = df['platforms'].str.contains('windows', case=False)
df['is_mac'] = df['platforms'].str.contains('mac', case=False)
df['is_linux'] = df['platforms'].str.contains('linux', case=False)
df[['platforms', 'is_windows', 'is_mac', 'is_linux']].head()

           platforms  is_windows  is_mac  is_linux
0  windows;mac;linux        True    True      True
1  windows;mac;linux        True    True      True
2  windows;mac;linux        True    True      True
3  windows;mac;linux        True    True      True
4  windows;mac;linux        True    True      True

In [8]:
#cantidad de nulos por columna
df.isnull().sum()

appid                0
name                 0
release_date         0
english              0
developer            1
publisher           14
platforms            0
required_age         0
categories           0
genres               0
steamspy_tags        0
achievements         0
positive_ratings     0
negative_ratings     0
average_playtime     0
median_playtime      0
owners               0
price                0
dtype: int64

Al revisar la estructura de los datos, detectamos que las columnas developer y publisher contienen valores nulos (1 y 14 respectivamente). Dado que 15 registros representan apenas el 0.05% del total de 27.075 juegos, la estrategia más eficiente y que menos impacto tiene en la varianza del dataset es eliminar estas filas incompletas utilizando métodos nativos de Pandas.

In [12]:
# Comprobar la cantidad exacta de nulos por columna
print("Nulos antes de la limpieza:")
display(df.isnull().sum()[df.isnull().sum() > 0])

Nulos antes de la limpieza:

developer     1
publisher    14
dtype: int64

In [13]:
# Eliminar las filas que contengan valores nulos en esas columnas específicas
df_limpio = df.dropna(subset=['developer', 'publisher']).copy()

In [14]:
# Verificar que el dataset quedó limpio y ver la nueva dimensión
print(f"\nLimpieza completada. Las nuevas dimensiones son: {df_limpio.shape[0]} filas y {df_limpio.shape[1]} columnas.")

Limpieza completada. Las nuevas dimensiones son: 27061 filas y 21 columnas.